version: "3"
services:
  app:
    build: ./dockerfiles/app
    volumes:
      - ./todo_tutorial:/app
    ports:
      - "4000:4000"
    environment:
      - PHOENIX_VERSION=${PHOENIX_VERSION}
  postgres:
    build: ./dockerfiles/db
    volumes:
      - ${DATA_PATH_HOST}/${COMPOSE_PROJECT_NAME}/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  